version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: pianomisspass-postgres
    environment:
      POSTGRES_DB: PianoMissPassDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pianomisspass_pgdata:/var/lib/postgresql/data

volumes:
  pianomisspass_pgdata:
